[general]
source_path = "src/"          # 需要扫描的源码路径
output_path = "ast.db"        # 输出数据库路径

[compilation]
# 编译设置

include_paths = [             # include path
    "/usr/local/include",
    "third_party/boost_1.83",
    "src/core/include",
]

defines = [         # 预定义宏
    "DEBUG_MODE=1",   # 带值的宏
    "USE_FAST_ALGO",  # 无值宏
    "MAX_ITEMS=1000", # 数值宏
]

cxx_standard = "c++17" # C++标准版本

flags = [              # 编译器标志
    "-fexceptions",
    "-Wno-deprecated",
]

[database]
# 数据库连接参数

batch_size = 1000        # 批量写入记录数
cache_size_mb = 64       # SQLite缓存大小（MB）
journal_mode = "WAL"     # 日志模式
synchronous = "NORMAL"   # 同步模式

[logging]
# 日志设置

level = "DEBUG"              # 日志级别（DEBUG/INFO/WARN/ERROR）
file = ""                    # 日志文件路径(为空则不输出至文件)
is_to_console = true         # 是否输出到控制台
batch_size = 5               # 日志批量写入记录数
enable_perf_logging = false  # 是否记录性能日志
